export type NavItem = { href: string; label: string; icon: string; group?: string };

export const navItems: NavItem[] = [
  { href: "/dashboard", label: "Dashboard", icon: "LayoutDashboard" },
  { href: "/timeline", label: "Timeline", icon: "Calendar" },
  { href: "/scenarios", label: "Scenario Simulator", icon: "TrendingUp" },
  { href: "/net-worth", label: "Net Worth", icon: "LineChart" },
  { href: "/debt", label: "Debt Planner", icon: "Activity" },
  { href: "/portfolios", label: "Portfolios", icon: "Wallet" },
  { href: "/currency", label: "Currency Desk", icon: "ArrowLeftRight" },
  { href: "/connectors", label: "Sync Hub", icon: "RefreshCw" },
  { href: "/workspaces", label: "Workspaces", icon: "Users" },
  { href: "/investments", label: "Investments", icon: "TrendingUp" },
  { href: "/retirement", label: "Retirement Planner", icon: "Target" },
  { href: "/tax", label: "Tax Planning", icon: "FileText" },
  { href: "/risk", label: "Risk Management", icon: "Shield" },
  { href: "/collaboration", label: "Collaboration Desk", icon: "Users" },
  { href: "/command-center", label: "Command Center", icon: "LayoutGrid" },
  { href: "/agents", label: "AI Orchestrator", icon: "Cpu" },
  { href: "/developer", label: "Developer Tools", icon: "Code" },
  { href: "/copilot", label: "AI Copilot", icon: "Sparkles" },
  { href: "/offline", label: "Offline Sync", icon: "WifiOff" },
  { href: "/transactions", label: "Transactions", icon: "ArrowLeftRight" },
  { href: "/categories", label: "Categories", icon: "Tags" },
  { href: "/budgets", label: "Budgets", icon: "Wallet" },
  { href: "/goals", label: "Goals", icon: "Target" },
  { href: "/emergency-fund", label: "Emergency Fund", icon: "Shield" },
  { href: "/documents", label: "Receipt Scanner", icon: "FileText" },
  { href: "/exchange", label: "Data Exchange", icon: "Database" },
  { href: "/automation", label: "Automation", icon: "Cpu" },
  { href: "/insights", label: "Insights", icon: "Sparkles" },
  { href: "/score", label: "Health Score", icon: "Activity" },
  { href: "/spending", label: "Spending Intelligence", icon: "LineChart" },
  { href: "/recommendations", label: "Recommendations", icon: "Lightbulb" },
  { href: "/forecasts", label: "Forecasts", icon: "TrendingUp" },
  { href: "/ai-insights", label: "AI Insights", icon: "Sparkles" },
  { href: "/profile", label: "Profile", icon: "User" },
  { href: "/settings", label: "Settings", icon: "Settings" },
];
